server:
  port: 8080

spring:
  profiles:
    active: local
    include: oauth, aws

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  config: classpath:logback/logback.xml
  level:
    com.withus.be: debug
